version: '3'


services:
     redis:
       image: bitnami/redis:6.2
       environment:
         - REDIS_PASSWORD=r3d1sp4ssw0rd
       ports:
         - "6379:6379"
       restart: unless-stopped
     redis-commander:
       image: rediscommander/redis-commander:latest
       environment:
         - REDIS_HOSTS=local:redis:6379:0:r3d1sp4ssw0rd
         - HTTP_USER=redis_user
         - HTTP_PASSWORD=asdf1234
       ports:
         - "8085:8081"
       depends_on:
         - redis
       restart: unless-stopped
